title: Morgane Ohlig
logo: /assets/img/me.png
description: MEng Computer Science @ University College London. Systems and Networks Research Group.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github.repository_url: https://github.com/Foalfloater66
